version: "3.9"

services:
  automation-gui:
    image: node:18-bullseye-slim
    working_dir: /usr/src/app
    volumes:
      - ../apps/automation-gui:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=1
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    command: sh -lc "corepack enable && pnpm i && pnpm dev --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    restart: unless-stopped

  massive-multimodal:
    image: node:18-bullseye-slim
    working_dir: /usr/src/app
    volumes:
      - ../apps/massive-multimodal:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=1
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    command: sh -lc "corepack enable && pnpm i && pnpm dev --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    restart: unless-stopped

  massive-web:
    image: node:18-bullseye-slim
    working_dir: /usr/src/app
    volumes:
      - ../apps/massive-web:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=1
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    command: sh -lc "corepack enable && pnpm i && pnpm dev --host 0.0.0.0 --port 3002"
    ports:
      - "3002:3002"
    restart: unless-stopped

